# Generated by Django 4.1.7 on 2023-02-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="full name"),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="active status"),
                ),
                (
                    "password_reset_required",
                    models.BooleanField(
                        default=False, verbose_name="password reset status"
                    ),
                ),
                (
                    "is_admin",
                    models.BooleanField(default=False, verbose_name="admin status"),
                ),
                ("google_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="last login ip"
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date joined"
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
        ),
    ]
