# Generated by Django 4.1.7 on 2023-02-17 01:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("merchants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchant",
            name="business_country",
            field=models.CharField(
                choices=[("IND", "India"), ("USA", "United State of America")],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="company_logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="merchants/logos/"
            ),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="is_registered",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="merchant_id",
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
