# Generated by Django 4.1.7 on 2023-02-16 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("merchants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Settlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "settlement_id",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                ("amount", models.PositiveIntegerField()),
                ("currency", models.CharField(max_length=3)),
                ("scheduled_on", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("in_progress", "In Progress"),
                            ("complete", "Complete"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        max_length=15,
                    ),
                ),
                ("is_reschduled", models.BooleanField(default=False)),
                (
                    "merchant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="settlements",
                        to="merchants.merchant",
                    ),
                ),
            ],
            options={
                "db_table": "settlements",
            },
        ),
    ]
