# Generated by Django 4.1.7 on 2023-02-16 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("merchants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_live_mode", models.BooleanField(db_index=True, default=True)),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                ("amount", models.PositiveIntegerField()),
                ("amount_due", models.PositiveIntegerField()),
                ("currency", models.CharField(max_length=3)),
                ("attempts", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "CREATED"),
                            ("attempted", "ATTEMPTED"),
                            ("paid", "PAID"),
                        ],
                        default="created",
                        max_length=10,
                    ),
                ),
                ("notes", models.JSONField(blank=True, null=True)),
                ("receipt", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "merchant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="merchants.merchant",
                    ),
                ),
            ],
            options={
                "db_table": "transactions",
            },
        ),
    ]
