# Generated by Django 4.1.7 on 2023-02-19 15:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="amount_due",
        ),
    ]
