# Generated by Django 4.1.7 on 2023-02-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("transactions", "0003_alter_transaction_transaction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="currency",
            field=models.CharField(
                choices=[("INR", "INR"), ("USD", "USD")], max_length=3
            ),
        ),
    ]
