# Generated by Django 4.1.7 on 2023-02-21 01:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("merchants", "0005_delete_collaborator"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("collaborators", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="collaborator",
            unique_together={("merchant", "user")},
        ),
    ]
