# Generated by Django 4.1.7 on 2023-02-16 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("merchants", "0001_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="charges",
            new_name="service_charges",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="method",
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("card", "Card"),
                    ("net_banking", "Net Banking"),
                    ("wallet", "Wallet"),
                    ("upi", "UPI"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="refunded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="card_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("debit", "Debit"),
                    ("credit", "Credit"),
                    ("unknown", "Unknown"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="merchant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="merchants.merchant",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="refund_status",
            field=models.CharField(
                blank=True,
                choices=[("partial", "Partial"), ("full", "Full")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("authorized", "Authorized"),
                    ("captured", "Captured"),
                    ("refunded", "Refunded"),
                    ("failed", "Failed"),
                ],
                default="created",
                max_length=10,
            ),
        ),
    ]
