# Generated by Django 4.1.7 on 2023-02-21 01:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0004_alter_payment_payment_id_alter_payment_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="card_network",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
